
// This file is autogenerated by the Firebase tooling.
// Editing this file is not recommended.
import {initializeApp, getApps, getApp, type FirebaseApp} from 'firebase/app';
import {getAuth, type Auth} from 'firebase/auth';
import {getFirestore, type Firestore} from 'firebase/firestore';

const firebaseConfig = {"apiKey":"AIzaSyB-On5YA8yDiRL53z3OV-QWaKzAThj7kQ4","authDomain":"workwell-c4rlk.firebaseapp.com","projectId":"workwell-c4rlk","storageBucket":"workwell-c4rlk.appspot.com","messagingSenderId":"1051738167084","appId":"1:1051738167084:web:db1c791c01876b69c5be89"};

function initializeFirebase() {
  if (getApps().length) {
    const app = getApp();
    const auth = getAuth(app);
    const db = getFirestore(app);
    return {app, auth, db};
  } else {
    const app = initializeApp(firebaseConfig);
    const auth = getAuth(app);
    const db = getFirestore(app);
    return {app, auth, db};
  }
}

const {app, auth, db} = initializeFirebase();

export {app, auth, db};
