// This file is autogenerated by the Firebase tooling.
// Editing this file is not recommended.
import {initializeApp, getApps, getApp, type FirebaseApp} from 'firebase/app';
import {getAuth, type Auth} from 'firebase/auth';
import {getFirestore, type Firestore} from 'firebase/firestore';

const firebaseConfig = {"apiKey":"AIzaSyB-On5YA8yDiRL53z3OV-QWaKzAThj7kQ4","authDomain":"workwell-c4rlk.firebaseapp.com","projectId":"workwell-c4rlk","storageBucket":"workwell-c4rlk.appspot.com","messagingSenderId":"1051738167084","appId":"1:1051738167084:web:db1c791c01876b69c5be89"};

// Initialize Firebase for server-side if needed, but client will have its own
let app: FirebaseApp;
if (!getApps().length) {
  app = initializeApp(firebaseConfig);
} else {
  app = getApp();
}

const db = getFirestore(app);
const auth = getAuth(app);

export { db, auth, app, firebaseConfig };
